// This file is autogenerated by "./scripts/generate-icon-types.js". Do not edit it manually.

export enum IconName {
  Eye = "eye",
  Star = "star",
  Compare = "compare",
  Question = "question",
  Share = "share",
  Delivery = "delivery",
  Shipping = "shipping",
  ChevronLeft = "chevron-left",
  ChevronRight = "chevron-right",
  ChevronDown = "chevron-down",
  Check = "check",
  ArrowUp = "arrow-up",
  Cart = "cart",
  Menu = "menu",
  Close = "close"
}
