name: 🚀 Deploy to GitHub Pages on push to 'main'
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4.1.6

    - name: 🔧 Install and Build
      run: |
        npm install
        npm run build

    - name: 🚀 Deploy
      uses: JamesIves/github-pages-deploy-action@v4.6.1
      with:
        folder: dist
